### PR TITLE
Add connection to MongoDB and create .env file in server folder

### PR DESCRIPTION
**Pull request by karimahcodes**
This fixes issue #3. Please review. We may need to review our server folder later.

### CODE REVIEW

**Review by Esterjudith — APPROVED** [review]
Good Job, thank you Karimah

**Review by lellis09 — APPROVED** [review]

**Review by CodingLady22 — APPROVED** [review]

**Review by Esterjudith — CHANGES_REQUESTED** [review]
Remove .env

**Review by lellis09 — CHANGES_REQUESTED** [review]
NOPE

**Comment by karimahcodes** [comment]
Thanks! Looks like there is an issue with our .gitignore file. let's review.

**Review by CodingLady22 — APPROVED** [review]

**Pull request merged**
